# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=build
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),build)
  AdventOfCode_config = build
endif

PROJECTS := AdventOfCode

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

AdventOfCode:
ifneq (,$(AdventOfCode_config))
	@echo "==== Building AdventOfCode ($(AdventOfCode_config)) ===="
	@${MAKE} --no-print-directory -C AdventOfCode -f Makefile config=$(AdventOfCode_config)
endif

clean:
	@${MAKE} --no-print-directory -C AdventOfCode -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  build"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   AdventOfCode"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"